from __future__ import annotations

import hashlib
import ipaddress
import os
import re
import tempfile
from pathlib import Path
from typing import Any

from .admin import SettingsStore
from .ami import AsteriskAMI


class TelephonyConfigSync:
    """Render DB-managed SIP and DID objects into internal Asterisk include files."""

    def __init__(self, store: SettingsStore, ami: AsteriskAMI, path: str):
        self.store = store
        self.ami = ami
        self.path = Path(path)
        self.dialplan_path = self.path.with_name("extensions.dynamic.conf")
        self.voicemail_path = self.path.with_name("voicemail.dynamic.conf")
        self.transports_path = self.path.with_name("pjsip.transports.conf")
        self.path.parent.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _id(prefix: str, value: str) -> str:
        return f"{prefix}-{hashlib.sha256(value.encode()).hexdigest()[:12]}"

    @staticmethod
    def _clean(value: Any) -> str:
        text = str(value or "")
        if "\n" in text or "\r" in text or ";" in text or "#" in text:
            raise ValueError("Telephony configuration contains an invalid character")
        return text

    @staticmethod
    def _codecs(value: str) -> str:
        allowed = {"ulaw", "alaw", "opus", "g722", "gsm", "slin", "slin16"}
        codecs = [item.strip().lower() for item in value.split(",") if item.strip()]
        if not codecs or any(codec not in allowed for codec in codecs):
            raise ValueError("Unsupported SIP codec configuration")
        if not ({"ulaw", "alaw"} & set(codecs)):
            raise ValueError("Provider must allow ulaw or alaw to interoperate with internal extensions")
        return ",".join(dict.fromkeys(codecs))

    @staticmethod
    def _transport(value: str) -> str:
        value = value.strip().lower()
        if value not in {"udp", "tcp"}:
            raise ValueError("Provider transport must be udp or tcp")
        return value

    @staticmethod
    def _allowed_ips(value: str) -> list[str]:
        result = []
        for item in str(value or "").split(","):
            item = item.strip()
            if not item:
                continue
            try:
                result.append(str(ipaddress.ip_network(item, strict=False)))
            except ValueError as exc:
                raise ValueError(f"Invalid provider IP/CIDR: {item}") from exc
        return list(dict.fromkeys(result))

    @staticmethod
    def _valid_extension(value: str) -> bool:
        return value.isdigit() and 100 <= int(value) <= 999

    def _fallback_extension(self, configured: str, active_extensions: list[str]) -> str:
        if configured and self._valid_extension(configured) and configured in active_extensions:
            return configured
        if active_extensions:
            return active_extensions[0]
        return "101"

    def _outbound_identity(self, extension: str) -> tuple[str, str]:
        """Caller ID and carrier trunk a phone on this extension dials out
        with: its default outbound DID and that number's provider endpoint.
        Empty strings mean the extension has no number - direct outbound
        calls from it are refused by the dialplan."""
        assigned = self.store.get_outbound_number(extension)
        if not assigned:
            return "", ""
        provider = None
        if assigned.get("provider"):
            provider = self.store.get_provider(str(assigned["provider"]))
        if provider is None:
            provider = self.store.get_provider()
        if not provider:
            return "", ""
        return self._clean(str(assigned["number"])), self._id("provider", self._clean(str(provider["name"])))

    # Traffic to these destinations is never NAT-rewritten to the external
    # address (Docker networks and RFC1918 LANs).
    LOCAL_NETS = ("10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16")

    def external_address(self) -> str:
        """Single source of truth for the public SIP/RTP address: the admin
        panel's Service address (service_host). ASTERISK_EXTERNAL_ADDRESS in
        .env is only the bootstrap fallback until it is configured."""
        configured = self._clean(self.store.get_settings().get("service_host") or "").strip()
        return configured or self._clean(os.environ.get("ASTERISK_EXTERNAL_ADDRESS", "")).strip()

    def render_transports(self) -> str:
        external = self.external_address()
        lines = [
            "; AUTO-GENERATED by EngineerIP Telephony. Do not edit manually.",
            "; The public address comes from the admin panel (Settings -> Service",
            "; address); ASTERISK_EXTERNAL_ADDRESS in .env is only a bootstrap",
            "; fallback. Transport changes are applied when Asterisk restarts.",
            "",
        ]
        for proto in ("udp", "tcp"):
            lines.extend([f"[transport-{proto}]", "type=transport", f"protocol={proto}", "bind=0.0.0.0:5060"])
            if external:
                lines.extend([
                    f"external_media_address={external}",
                    f"external_signaling_address={external}",
                    *[f"local_net={net}" for net in self.LOCAL_NETS],
                ])
            lines.append("")
        return "\n".join(lines)

    def _auth_digest_lines(self) -> list[str]:
        """Digest algorithm(s) Asterisk offers when challenging a phone,
        chosen by the administrator (Settings -> Server addresses).

        md5 (default) omits the option entirely - Asterisk challenges with
        plain MD5, which every softphone supports. sha256 and both emit the
        matching supported_algorithms_uas value; note that some clients
        (e.g. Zoiper 5) abandon a challenge that contains SHA-256."""
        choice = str(self.store.get_settings().get("sip_auth_digest") or "md5").strip().lower()
        if choice == "sha256":
            return ["supported_algorithms_uas=SHA-256"]
        if choice == "both":
            return ["supported_algorithms_uas=SHA-256,MD5"]
        return []

    def render_pjsip(self) -> str:
        lines = [
            "; AUTO-GENERATED by EngineerIP Telephony. Do not edit manually.",
            "; This file contains SIP credentials and is shared only on the internal Docker network.",
            "",
        ]
        # A customer SIP account linked to an extension becomes that extension's
        # live PJSIP credential, so credentials shown in the portal really ring.
        sip_accounts = [row for row in self.store.list_sip_accounts(include_password=True) if row["active"]]
        sip_by_extension = {str(row["extension"]): row for row in sip_accounts if row.get("extension")}
        # Admin-chosen digest challenge (md5/sha256/both), same for every account.
        auth_digest = self._auth_digest_lines()
        configured_extensions: set[str] = set()
        for ext in self.store.list_extensions():
            if not ext["active"]:
                continue
            extension = self._clean(ext["extension"])
            linked = sip_by_extension.get(extension)
            username = self._clean(linked["sip_username"] if linked else ext["sip_username"])
            password = self._clean(linked["sip_password"] if linked else self.store.get_extension_password(extension))
            transport = self._transport(linked["transport"] if linked else "udp")
            configured_extensions.add(extension)
            # A phone signs in with its prefixed SIP username (e.g. AUHFZH_101)
            # in the From/To headers and the Authorization header, while the
            # dialplan dials the endpoint by extension number. PJSIP's
            # username/auth_username identifiers match against the endpoint
            # NAME, so three objects make the login work:
            #   - an AOR named after the username (the registrar resolves the
            #     To-user against the matched endpoint's AOR list),
            #   - an alias ENDPOINT named after the username sharing the same
            #     auth and AORs (so REGISTER/INVITE from the phone are matched
            #     and authenticated at all),
            #   - the canonical [extension] endpoint the dialplan dials; its
            #     aors list includes the alias AOR, so it rings the phone
            #     wherever the contact was registered.
            outbound_cid, outbound_trunk = self._outbound_identity(extension)
            aors = [extension]
            alias_aor = []
            if username != extension:
                aors.append(username)
                alias_aor = [f"[{username}]", "type=aor", "max_contacts=5", "remove_existing=yes", ""]
            endpoint_body = [
                "context=from-internal", "disallow=all", "allow=ulaw,alaw", f"transport=transport-{transport}",
                "direct_media=no", "rtp_symmetric=yes", "force_rport=yes", "rewrite_contact=yes",
                "identify_by=username,auth_username",
                f"set_var=OUTBOUND_CID={outbound_cid}", f"set_var=OUTBOUND_TRUNK={outbound_trunk}",
                f"allow_subscribe={'yes' if ext.get('voicemail_enabled') else 'no'}",
                *([f"mailboxes={extension}@engineerip"] if ext.get("voicemail_enabled") else []),
            ]
            alias_endpoint = []
            if username != extension:
                alias_endpoint = [
                    f"[{username}]", "type=endpoint", f"aors={','.join(aors)}", f"auth=auth-{extension}",
                    f"callerid=<{extension}>", *endpoint_body, "",
                ]
            lines.extend([
                f"; Extension {extension}",
                f"[{extension}]", "type=aor", "max_contacts=5", "remove_existing=yes", "",
                *alias_aor,
                f"[auth-{extension}]", "type=auth", "auth_type=userpass",
                f"username={username}", f"password={password}", *auth_digest, "",
                f"[{extension}]", "type=endpoint", f"aors={','.join(aors)}", f"auth=auth-{extension}",
                *endpoint_body, "",
                *alias_endpoint,
            ])

        for account in sip_accounts:
            extension = self._clean(str(account.get("extension") or ""))
            if extension in configured_extensions:
                continue
            endpoint = self._id("device", str(account["sip_username"]))
            username = self._clean(account["sip_username"])
            password = self._clean(account["sip_password"])
            transport = self._transport(account["transport"])
            # Same registration contract as extensions: the device signs in
            # with its SIP username, so that name must exist both as an AOR
            # (for the registrar) and as an alias ENDPOINT (for endpoint
            # identification - PJSIP matches usernames against endpoint
            # names, and this endpoint's own name is an internal hash).
            outbound_cid, outbound_trunk = self._outbound_identity(extension) if extension else ("", "")
            device_body = [
                "context=from-internal", "disallow=all", "allow=ulaw,alaw", f"transport=transport-{transport}",
                "direct_media=no", "rtp_symmetric=yes", "force_rport=yes", "rewrite_contact=yes",
                "identify_by=username,auth_username",
                f"set_var=OUTBOUND_CID={outbound_cid}", f"set_var=OUTBOUND_TRUNK={outbound_trunk}",
            ]
            lines.extend([
                f"; Customer device {username}",
                f"[{endpoint}]", "type=aor", "max_contacts=5", "remove_existing=yes", "",
                f"[{username}]", "type=aor", "max_contacts=5", "remove_existing=yes", "",
                f"[auth-{endpoint}]", "type=auth", "auth_type=userpass", f"username={username}", f"password={password}", *auth_digest, "",
                f"[{endpoint}]", "type=endpoint", f"aors={endpoint},{username}", f"auth=auth-{endpoint}",
                *device_body, "",
                f"[{username}]", "type=endpoint", f"aors={endpoint},{username}", f"auth=auth-{endpoint}",
                *device_body, "",
            ])

        for provider in self.store.list_provider_details():
            if not provider["active"]:
                continue
            name = self._clean(provider["name"])
            server = self._clean(provider["server"])
            username = self._clean(provider["username"])
            password = self._clean(provider["password"])
            port = int(provider["port"])
            if not 1 <= port <= 65535:
                raise ValueError("Provider port is invalid")
            transport = self._transport(provider["transport"])
            codecs = self._codecs(provider["codecs"])
            endpoint = self._id("provider", name)
            auth = f"{endpoint}-auth"
            registration = f"{endpoint}-reg"
            did = self.store.first_active_number_for_provider(name)
            did_user = re.sub(r"[^0-9]", "", did or "")
            lines.extend([
                f"; SIP provider {name}", f"[{endpoint}]", "type=endpoint", f"transport=transport-{transport}",
                "context=from-provider", "disallow=all", f"allow={codecs}", f"outbound_auth={auth}",
                f"aors={endpoint}", "direct_media=no", "rtp_symmetric=yes", "force_rport=yes", "rewrite_contact=yes",
                "send_pai=yes", "send_rpid=yes", "trust_id_outbound=yes",
                f"from_user={username}", f"from_domain={server}", "",
                f"[{auth}]", "type=auth", "auth_type=userpass", f"username={username}", f"password={password}", "",
                f"[{endpoint}]", "type=aor", f"contact=sip:{server}:{port}", "qualify_frequency=60", "",
                f"[{registration}]", "type=registration", f"transport=transport-{transport}", f"outbound_auth={auth}",
                f"server_uri=sip:{server}:{port}", f"client_uri=sip:{username}@{server}",
                *([f"contact_user={did_user}"] if did_user else []), "retry_interval=30",
                "forbidden_retry_interval=300", "expiration=300", "",
            ])
            allowed_ips = self._allowed_ips(provider.get("allowed_ips", ""))
            if not allowed_ips:
                raise ValueError(f"Provider {name} has no inbound IP/CIDR allowlist")
            for index, match in enumerate(allowed_ips, 1):
                lines.extend([
                    f"[{endpoint}-identify-{index}]", "type=identify", f"endpoint={endpoint}", f"match={match}", "",
                ])
        return "\n".join(lines) + "\n"

    def render_voicemail(self) -> str:
        lines = [
            "; AUTO-GENERATED EngineerIP voicemail mailboxes.",
            "[engineerip]",
        ]
        for extension in self.store.list_extensions():
            if not extension["active"] or not extension.get("voicemail_enabled"):
                continue
            number = self._clean(extension["extension"])
            pin = self._clean(self.store.get_voicemail_pin(number))
            display_name = self._clean(extension.get("display_name") or f"Extension {number}")
            lines.append(f"{number} => {pin},{display_name},,,attach=no|delete=no")
        lines.append("")
        return "\n".join(lines)

    def render_dialplan(self) -> str:
        settings = self.store.get_settings()
        extensions = [row for row in self.store.list_extensions() if row["active"]]
        active_exts = [row["extension"] for row in extensions]
        voicemail_exts = {row["extension"] for row in extensions if row.get("voicemail_enabled")}
        default_ext = self._fallback_extension(str(settings.get("default_extension", "")).strip(), active_exts)
        inbound_fallback = self._fallback_extension(
            str(settings.get("inbound_fallback_extension", "")).strip(), active_exts
        )

        def did_extension(number) -> str:
            """Which extension answers this DID when its own link is missing or stale.

            Each customer chooses their own fallback, so an unassigned DID belonging
            to one customer can never land on another customer's phone. The
            platform-wide values below are only a last resort for rows written
            before customers owned this decision.
            """
            owner = number.get("owner_user_id")
            if owner is not None:
                customer = self.store.customer_call_defaults(int(owner)).get("fallback", "")
                if customer and customer in active_exts:
                    return customer
            return inbound_fallback

        lines = [
            "; AUTO-GENERATED EngineerIP DID and voicemail routing.",
            "[from-internal]",
            "exten => *97,1,NoOp(EngineerIP voicemail login)",
            " same => n,VoiceMailMain(@engineerip)",
            " same => n,Hangup()",
        ]
        for extension in extensions:
            number = extension["extension"]
            lines.extend([
                f"exten => {number},1,NoOp(EngineerIP extension {number})",
                f" same => n,Dial(PJSIP/{number},30)",
                *([f' same => n,ExecIf($["${{DIALSTATUS}}" != "ANSWER"]?VoiceMail({number}@engineerip,u))'] if number in voicemail_exts else []),
                " same => n,Hangup()",
            ])
        # Direct outbound dialing from a registered phone. The calling
        # endpoint carries its own caller ID and carrier trunk as channel
        # variables (set_var in pjsip, see render_pjsip) - an endpoint
        # without an assigned number is politely refused instead of
        # leaking another customer's identity.
        for pattern in ("_+X.", "_XXXX."):
            lines.extend([
                f"exten => {pattern},1,NoOp(Outbound ${{EXTEN}} from endpoint ${{CHANNEL(endpoint)}})",
                ' same => n,GotoIf($["${OUTBOUND_TRUNK}"=""]?blocked)',
                " same => n,Set(CALLERID(num)=${OUTBOUND_CID})",
                " same => n,Dial(PJSIP/${EXTEN}@${OUTBOUND_TRUNK},60)",
                " same => n,Hangup()",
                " same => n(blocked),NoOp(No outbound number assigned to endpoint ${CHANNEL(endpoint)})",
                " same => n,Playback(ss-noservice)",
                " same => n,Hangup()",
            ])
        lines.extend(["", "[voicemail-inbound]"])
        for extension in sorted(voicemail_exts):
            lines.extend([
                f"exten => {extension},1,VoiceMail({extension}@engineerip,u)",
                " same => n,Hangup()",
            ])
        lines.extend(["", "[from-provider]"])
        for number in self.store.list_numbers():
            if not number["active"]:
                continue
            did = re.sub(r"[^0-9]", "", number["number"])
            extension = number["inbound_extension"] or did_extension(number)
            if not did or not self._valid_extension(str(extension)) or str(extension) not in active_exts:
                extension = inbound_fallback
            for dialed_number in (did, f"+{did}"):
                lines.extend([
                    f"exten => {dialed_number},1,NoOp(Inbound DID {dialed_number} owned by extension {extension})",
                    f" same => n,Stasis(engineerip,inbound,{dialed_number},{extension})",
                    *([f" same => n,VoiceMail({extension}@engineerip,u)"] if extension in voicemail_exts else []),
                    " same => n,Hangup()",
                ])
        lines.extend([
            "exten => s,1,NoOp(Inbound provider call ${CALLERID(all)})",
            f" same => n,Dial(PJSIP/{default_ext},30)",
            *([f' same => n,ExecIf($["${{DIALSTATUS}}" != "ANSWER"]?VoiceMail({default_ext}@engineerip,u))'] if default_ext in voicemail_exts else []),
            " same => n,Hangup()",
            "",
        ])
        return "\n".join(lines)

    def _atomic_write(self, path: Path, content: str) -> None:
        fd, tmp_name = tempfile.mkstemp(prefix=path.stem + ".", suffix=".tmp", dir=str(path.parent))
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())
            os.chmod(tmp_name, 0o644)
            os.replace(tmp_name, path)
        finally:
            if os.path.exists(tmp_name):
                os.unlink(tmp_name)

    def apply(self) -> None:
        self._atomic_write(self.transports_path, self.render_transports())
        self._atomic_write(self.path, self.render_pjsip())
        self._atomic_write(self.dialplan_path, self.render_dialplan())
        self._atomic_write(self.voicemail_path, self.render_voicemail())
        self.ami.reload_pjsip()
        self.ami.reload_voicemail()
        self.ami.reload_dialplan()
