from __future__ import annotations

import hashlib
import ipaddress
import os
import re
import tempfile
from pathlib import Path
from typing import Any

from .admin import SettingsStore
from .ami import AsteriskAMI


class TelephonyConfigSync:
    """Render DB-managed SIP and DID objects into internal Asterisk include files."""

    def __init__(self, store: SettingsStore, ami: AsteriskAMI, path: str):
        self.store = store
        self.ami = ami
        self.path = Path(path)
        self.dialplan_path = self.path.with_name("extensions.dynamic.conf")
        self.voicemail_path = self.path.with_name("voicemail.dynamic.conf")
        self.path.parent.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _id(prefix: str, value: str) -> str:
        return f"{prefix}-{hashlib.sha256(value.encode()).hexdigest()[:12]}"

    @staticmethod
    def _clean(value: Any) -> str:
        text = str(value or "")
        if "\n" in text or "\r" in text or ";" in text or "#" in text:
            raise ValueError("Telephony configuration contains an invalid character")
        return text

    @staticmethod
    def _codecs(value: str) -> str:
        allowed = {"ulaw", "alaw", "opus", "g722", "gsm", "slin", "slin16"}
        codecs = [item.strip().lower() for item in value.split(",") if item.strip()]
        if not codecs or any(codec not in allowed for codec in codecs):
            raise ValueError("Unsupported SIP codec configuration")
        if not ({"ulaw", "alaw"} & set(codecs)):
            raise ValueError("Provider must allow ulaw or alaw to interoperate with internal extensions")
        return ",".join(dict.fromkeys(codecs))

    @staticmethod
    def _transport(value: str) -> str:
        value = value.strip().lower()
        if value not in {"udp", "tcp"}:
            raise ValueError("Provider transport must be udp or tcp")
        return value

    @staticmethod
    def _allowed_ips(value: str) -> list[str]:
        result = []
        for item in str(value or "").split(","):
            item = item.strip()
            if not item:
                continue
            try:
                result.append(str(ipaddress.ip_network(item, strict=False)))
            except ValueError as exc:
                raise ValueError(f"Invalid provider IP/CIDR: {item}") from exc
        return list(dict.fromkeys(result))

    @staticmethod
    def _valid_extension(value: str) -> bool:
        return value.isdigit() and 100 <= int(value) <= 999

    def _fallback_extension(self, configured: str, active_extensions: list[str]) -> str:
        if configured and self._valid_extension(configured) and configured in active_extensions:
            return configured
        if active_extensions:
            return active_extensions[0]
        return "101"

    def render_pjsip(self) -> str:
        lines = [
            "; AUTO-GENERATED by EngineerIP Telephony. Do not edit manually.",
            "; This file contains SIP credentials and is shared only on the internal Docker network.",
            "",
        ]
        # A customer SIP account linked to an extension becomes that extension's
        # live PJSIP credential, so credentials shown in the portal really ring.
        sip_accounts = [row for row in self.store.list_sip_accounts(include_password=True) if row["active"]]
        sip_by_extension = {str(row["extension"]): row for row in sip_accounts if row.get("extension")}
        configured_extensions: set[str] = set()
        for ext in self.store.list_extensions():
            if not ext["active"]:
                continue
            extension = self._clean(ext["extension"])
            linked = sip_by_extension.get(extension)
            username = self._clean(linked["sip_username"] if linked else ext["sip_username"])
            password = self._clean(linked["sip_password"] if linked else self.store.get_extension_password(extension))
            transport = self._transport(linked["transport"] if linked else "udp")
            configured_extensions.add(extension)
            lines.extend([
                f"; Extension {extension}",
                f"[{extension}]", "type=aor", "max_contacts=5", "remove_existing=yes", "",
                f"[auth-{extension}]", "type=auth", "auth_type=userpass",
                f"username={username}", f"password={password}", "supported_algorithms_uas=SHA-256,MD5", "",
                f"[{extension}]", "type=endpoint", f"aors={extension}", f"auth=auth-{extension}",
                "context=from-internal", "disallow=all", "allow=ulaw,alaw", f"transport=transport-{transport}",
                "direct_media=no", "rtp_symmetric=yes", "force_rport=yes", "rewrite_contact=yes",
                f"allow_subscribe={'yes' if ext.get('voicemail_enabled') else 'no'}",
                *([f"mailboxes={extension}@engineerip"] if ext.get("voicemail_enabled") else []), "",
            ])

        for account in sip_accounts:
            extension = self._clean(str(account.get("extension") or ""))
            if extension in configured_extensions:
                continue
            endpoint = self._id("device", str(account["sip_username"]))
            username = self._clean(account["sip_username"])
            password = self._clean(account["sip_password"])
            transport = self._transport(account["transport"])
            lines.extend([
                f"; Customer device {username}",
                f"[{endpoint}]", "type=aor", "max_contacts=5", "remove_existing=yes", "",
                f"[auth-{endpoint}]", "type=auth", "auth_type=userpass", f"username={username}", f"password={password}", "",
                f"[{endpoint}]", "type=endpoint", f"aors={endpoint}", f"auth=auth-{endpoint}",
                "context=from-internal", "disallow=all", "allow=ulaw,alaw", f"transport=transport-{transport}",
                "direct_media=no", "rtp_symmetric=yes", "force_rport=yes", "rewrite_contact=yes", "",
            ])

        for provider in self.store.list_provider_details():
            if not provider["active"]:
                continue
            name = self._clean(provider["name"])
            server = self._clean(provider["server"])
            username = self._clean(provider["username"])
            password = self._clean(provider["password"])
            port = int(provider["port"])
            if not 1 <= port <= 65535:
                raise ValueError("Provider port is invalid")
            transport = self._transport(provider["transport"])
            codecs = self._codecs(provider["codecs"])
            endpoint = self._id("provider", name)
            auth = f"{endpoint}-auth"
            registration = f"{endpoint}-reg"
            did = self.store.first_active_number_for_provider(name)
            did_user = re.sub(r"[^0-9]", "", did or "")
            lines.extend([
                f"; SIP provider {name}", f"[{endpoint}]", "type=endpoint", f"transport=transport-{transport}",
                "context=from-provider", "disallow=all", f"allow={codecs}", f"outbound_auth={auth}",
                f"aors={endpoint}", "direct_media=no", "rtp_symmetric=yes", "force_rport=yes", "rewrite_contact=yes",
                "send_pai=yes", "send_rpid=yes", "trust_id_outbound=yes",
                f"from_user={username}", f"from_domain={server}", "",
                f"[{auth}]", "type=auth", "auth_type=userpass", f"username={username}", f"password={password}", "",
                f"[{endpoint}]", "type=aor", f"contact=sip:{server}:{port}", "qualify_frequency=60", "",
                f"[{registration}]", "type=registration", f"transport=transport-{transport}", f"outbound_auth={auth}",
                f"server_uri=sip:{server}:{port}", f"client_uri=sip:{username}@{server}",
                *([f"contact_user={did_user}"] if did_user else []), "retry_interval=30",
                "forbidden_retry_interval=300", "expiration=300", "",
            ])
            allowed_ips = self._allowed_ips(provider.get("allowed_ips", ""))
            if not allowed_ips:
                raise ValueError(f"Provider {name} has no inbound IP/CIDR allowlist")
            for index, match in enumerate(allowed_ips, 1):
                lines.extend([
                    f"[{endpoint}-identify-{index}]", "type=identify", f"endpoint={endpoint}", f"match={match}", "",
                ])
        return "\n".join(lines) + "\n"

    def render_voicemail(self) -> str:
        lines = [
            "; AUTO-GENERATED EngineerIP voicemail mailboxes.",
            "[engineerip]",
        ]
        for extension in self.store.list_extensions():
            if not extension["active"] or not extension.get("voicemail_enabled"):
                continue
            number = self._clean(extension["extension"])
            pin = self._clean(self.store.get_voicemail_pin(number))
            display_name = self._clean(extension.get("display_name") or f"Extension {number}")
            lines.append(f"{number} => {pin},{display_name},,,attach=no|delete=no")
        lines.append("")
        return "\n".join(lines)

    def render_dialplan(self) -> str:
        settings = self.store.get_settings()
        extensions = [row for row in self.store.list_extensions() if row["active"]]
        active_exts = [row["extension"] for row in extensions]
        voicemail_exts = {row["extension"] for row in extensions if row.get("voicemail_enabled")}
        default_ext = self._fallback_extension(str(settings.get("default_extension", "")).strip(), active_exts)
        inbound_fallback = self._fallback_extension(
            str(settings.get("inbound_fallback_extension", "")).strip(), active_exts
        )

        def did_extension(number) -> str:
            """Which extension answers this DID when its own link is missing or stale.

            Each customer chooses their own fallback, so an unassigned DID belonging
            to one customer can never land on another customer's phone. The
            platform-wide values below are only a last resort for rows written
            before customers owned this decision.
            """
            owner = number.get("owner_user_id")
            if owner is not None:
                customer = self.store.customer_call_defaults(int(owner)).get("fallback", "")
                if customer and customer in active_exts:
                    return customer
            return inbound_fallback

        lines = [
            "; AUTO-GENERATED EngineerIP DID and voicemail routing.",
            "[from-internal]",
            "exten => *97,1,NoOp(EngineerIP voicemail login)",
            " same => n,VoiceMailMain(@engineerip)",
            " same => n,Hangup()",
        ]
        for extension in extensions:
            number = extension["extension"]
            lines.extend([
                f"exten => {number},1,NoOp(EngineerIP extension {number})",
                f" same => n,Dial(PJSIP/{number},30)",
                *([f' same => n,ExecIf($["${{DIALSTATUS}}" != "ANSWER"]?VoiceMail({number}@engineerip,u))'] if number in voicemail_exts else []),
                " same => n,Hangup()",
            ])
        lines.extend(["", "[voicemail-inbound]"])
        for extension in sorted(voicemail_exts):
            lines.extend([
                f"exten => {extension},1,VoiceMail({extension}@engineerip,u)",
                " same => n,Hangup()",
            ])
        lines.extend(["", "[from-provider]"])
        for number in self.store.list_numbers():
            if not number["active"]:
                continue
            did = re.sub(r"[^0-9]", "", number["number"])
            extension = number["inbound_extension"] or did_extension(number)
            if not did or not self._valid_extension(str(extension)) or str(extension) not in active_exts:
                extension = inbound_fallback
            for dialed_number in (did, f"+{did}"):
                lines.extend([
                    f"exten => {dialed_number},1,NoOp(Inbound DID {dialed_number} owned by extension {extension})",
                    f" same => n,Stasis(engineerip,inbound,{dialed_number},{extension})",
                    *([f" same => n,VoiceMail({extension}@engineerip,u)"] if extension in voicemail_exts else []),
                    " same => n,Hangup()",
                ])
        lines.extend([
            "exten => s,1,NoOp(Inbound provider call ${CALLERID(all)})",
            f" same => n,Dial(PJSIP/{default_ext},30)",
            *([f' same => n,ExecIf($["${{DIALSTATUS}}" != "ANSWER"]?VoiceMail({default_ext}@engineerip,u))'] if default_ext in voicemail_exts else []),
            " same => n,Hangup()",
            "",
        ])
        return "\n".join(lines)

    def _atomic_write(self, path: Path, content: str) -> None:
        fd, tmp_name = tempfile.mkstemp(prefix=path.stem + ".", suffix=".tmp", dir=str(path.parent))
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())
            os.chmod(tmp_name, 0o644)
            os.replace(tmp_name, path)
        finally:
            if os.path.exists(tmp_name):
                os.unlink(tmp_name)

    def apply(self) -> None:
        self._atomic_write(self.path, self.render_pjsip())
        self._atomic_write(self.dialplan_path, self.render_dialplan())
        self._atomic_write(self.voicemail_path, self.render_voicemail())
        self.ami.reload_pjsip()
        self.ami.reload_voicemail()
        self.ami.reload_dialplan()
