from __future__ import annotations

import hashlib
import os
import re
import tempfile
from pathlib import Path
from typing import Any

from .admin import SettingsStore
from .ami import AsteriskAMI


class TelephonyConfigSync:
    """Render DB-managed SIP and DID objects into internal Asterisk include files."""

    def __init__(self, store: SettingsStore, ami: AsteriskAMI, path: str):
        self.store = store
        self.ami = ami
        self.path = Path(path)
        self.dialplan_path = self.path.with_name("extensions.dynamic.conf")
        self.path.parent.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _id(prefix: str, value: str) -> str:
        return f"{prefix}-{hashlib.sha256(value.encode()).hexdigest()[:12]}"

    @staticmethod
    def _clean(value: Any) -> str:
        text = str(value or "")
        if "\n" in text or "\r" in text:
            raise ValueError("Telephony configuration contains an invalid newline")
        return text

    @staticmethod
    def _codecs(value: str) -> str:
        allowed = {"ulaw", "alaw", "opus", "g722", "gsm", "slin", "slin16"}
        codecs = [item.strip().lower() for item in value.split(",") if item.strip()]
        if not codecs or any(codec not in allowed for codec in codecs):
            raise ValueError("Unsupported SIP codec configuration")
        return ",".join(dict.fromkeys(codecs))

    @staticmethod
    def _transport(value: str) -> str:
        value = value.strip().lower()
        if value not in {"udp", "tcp"}:
            raise ValueError("Provider transport must be udp or tcp")
        return value

    def render_pjsip(self) -> str:
        lines = [
            "; AUTO-GENERATED by EngineerIP Telephony. Do not edit manually.",
            "; Secrets in this file are protected by the Docker-internal volume.",
            "",
        ]
        for ext in self.store.list_extensions():
            if not ext["active"]:
                continue
            extension = self._clean(ext["extension"])
            username = self._clean(ext["sip_username"])
            password = self._clean(self.store.get_extension_password(extension))
            lines.extend([
                f"; Extension {extension}",
                f"[{extension}]", "type=aor", "max_contacts=5", "remove_existing=yes", "",
                f"[auth-{extension}]", "type=auth", "auth_type=userpass",
                f"username={username}", f"password={password}", "supported_algorithms_uas=SHA-256,MD5", "",
                f"[{extension}]", "type=endpoint", f"aors={extension}", f"auth=auth-{extension}",
                "context=from-internal", "disallow=all", "allow=ulaw,alaw", "transport=transport-udp",
                "direct_media=no", "rtp_symmetric=yes", "force_rport=yes", "rewrite_contact=yes",
                "allow_subscribe=no", "",
            ])

        for provider in self.store.list_provider_details():
            if not provider["active"]:
                continue
            name = self._clean(provider["name"])
            server = self._clean(provider["server"])
            username = self._clean(provider["username"])
            password = self._clean(provider["password"])
            port = int(provider["port"])
            if not 1 <= port <= 65535:
                raise ValueError("Provider port is invalid")
            transport = self._transport(provider["transport"])
            codecs = self._codecs(provider["codecs"])
            endpoint = self._id("provider", name)
            auth = f"{endpoint}-auth"
            registration = f"{endpoint}-reg"
            did = self.store.first_active_number_for_provider(name)
            did_user = re.sub(r"[^0-9]", "", did or "")
            lines.extend([
                f"; SIP provider {name}", f"[{endpoint}]", "type=endpoint", f"transport=transport-{transport}",
                "context=from-provider", "disallow=all", f"allow={codecs}", f"outbound_auth={auth}",
                f"aors={endpoint}", "direct_media=no", "rtp_symmetric=yes", "force_rport=yes", "rewrite_contact=yes",
                f"from_user={username}", f"from_domain={server}", "",
                f"[{auth}]", "type=auth", "auth_type=userpass", f"username={username}", f"password={password}", "",
                f"[{endpoint}]", "type=aor", f"contact=sip:{server}:{port}", "qualify_frequency=60", "",
                f"[{registration}]", "type=registration", f"transport=transport-{transport}", f"outbound_auth={auth}",
                f"server_uri=sip:{server}:{port}", f"client_uri=sip:{username}@{server}",
                *( [f"contact_user={did_user}"] if did_user else [] ), "retry_interval=30",
                "forbidden_retry_interval=300", "expiration=300", "",
            ])
        return "\n".join(lines) + "\n"

    def render_dialplan(self) -> str:
        settings = self.store.get_settings()
        default_ext = str(settings.get("default_extension", "")).strip()
        if not default_ext:
            active_exts = [row["extension"] for row in self.store.list_extensions() if row["active"]]
            default_ext = active_exts[0] if active_exts else "101"
        lines = [
            "; AUTO-GENERATED EngineerIP DID routing.",
            "[from-internal]",
            "exten => _1XX,1,NoOp(EngineerIP extension ${EXTEN})",
            " same => n,Dial(PJSIP/${EXTEN},30)",
            " same => n,Hangup()",
            "",
            "[from-provider]",
        ]
        for number in self.store.list_numbers():
            if not number["active"]:
                continue
            did = re.sub(r"[^0-9]", "", number["number"])
            extension = number["inbound_extension"] or default_ext
            if not did or not str(extension).isdigit():
                continue
            lines.extend([
                f"exten => {did},1,NoOp(Inbound DID {did})",
                f" same => n,Dial(PJSIP/{extension},30)",
                " same => n,Hangup()",
            ])
        lines.extend([
            "exten => s,1,NoOp(Inbound provider call ${CALLERID(all)})",
            f" same => n,Dial(PJSIP/{default_ext},30)",
            " same => n,Hangup()",
            "",
        ])
        return "\n".join(lines)

    def _atomic_write(self, path: Path, content: str) -> None:
        fd, tmp_name = tempfile.mkstemp(prefix=path.stem + ".", suffix=".tmp", dir=str(path.parent))
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())
            os.chmod(tmp_name, 0o600)
            os.replace(tmp_name, path)
        finally:
            if os.path.exists(tmp_name):
                os.unlink(tmp_name)

    def apply(self) -> None:
        self._atomic_write(self.path, self.render_pjsip())
        self._atomic_write(self.dialplan_path, self.render_dialplan())
        self.ami.reload_pjsip()
        self.ami.reload_dialplan()
