[modules]
autoload=yes

; Disable optional/deprecated modules that are not used by this deployment.
noload => cdr_custom.so
noload => cel_custom.so
noload => cdr_sqlite3_custom.so
noload => cel_sqlite3_custom.so
noload => res_hep_rtcp.so
noload => res_hep_pjsip.so
noload => res_phoneprov.so
noload => res_adsi.so
noload => app_getcpeid.so
noload => app_adsiprog.so
